In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from matplotlib import pyplot
%matplotlib inline

In [2]:
x_train_in = pd.read_csv('./Data/X_train.csv')
y_train_in = pd.read_csv('./Data/y_train.csv')
students_in = pd.read_csv('./Data/studs_info.csv')
x_test_send = pd.read_csv('./Data/X_test.csv')

In [3]:
y_train_in.index = y_train_in['index']
y_train_in = y_train_in.drop('index',axis=1)
x_train_in.index = x_train_in.iloc[:,0]
x_train_in = x_train_in.drop(x_train_in.columns[0],axis=1)
x_test_send.index = x_test_send.iloc[:,0]
x_test_send = x_test_send.drop(x_test_send.columns[0],axis=1)

In [4]:
x_train_in.head()

,STD_ID,НАПРАВЛЕНИЕ,ГОД,КУРС,СЕМЕСТР,АТТЕСТАЦИЯ,ДИСЦИПЛИНА
Unnamed: 0,,,,,,,
51081,175711,38.03.02 Менеджмент,2018-2019,2.0,4.0,Экзамен,Маркетинг
72921,100647,31.05.01 Лечебное дело,2015-2016,3.0,5.0,Экзамен,"Пропедевтика внутренних болезней, лучевая диаг..."
96438,199311,31.05.03 Стоматология,2019-2020,1.0,1.0,Экзамен,Химия
273044,162002,38.03.02 Менеджмент,2017-2018,2.0,3.0,Экзамен,Статистика
371309,108384,31.05.01 Лечебное дело,2018-2019,5.0,9.0,Экзамен,Педиатрия

In [5]:
y_train_in.head()

        mark
index
51081      5
72921      5
96438      5
273044     4
371309     3

In [6]:
students_in.head()

,STD_ID,number,Пол,Статус,Дата выпуска,Категория обучения,Форма обучения,Шифр,направление (специальность),,Образование,Дата выдачи,Что именно закончил
0,99136,13951.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2629.0,СР,2013-06-26 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
1,99112,13998.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,8240.0,СР,2012-06-23 00:00:00,"МОУ СОШ N 2, ПЕСТОВО"
2,99109,13999.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2314.0,СР,2013-06-25 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
3,99125,13953.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2345.0,СР,2013-06-23 00:00:00,"Гимназия ""ГАРМОНИЯ"""
4,100676,13950.0,М,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2650.0,СР,2012-06-29 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА

In [19]:
x_test_send.head()

,STD_ID,НАПРАВЛЕНИЕ,ГОД,КУРС,СЕМЕСТР,АТТЕСТАЦИЯ,ДИСЦИПЛИНА
Unnamed: 0,,,,,,,
56065,163261,35.03.04 Агрономия,2018-2019,3.0,5.0,Дифференцированный зачет,История
304637,162990,23.03.03 Эксплуатация транспортно-технологичес...,2019-2020,4.0,7.0,Экзамен,Сертификация и лицензирование в сфере производ...
177437,192595,40.03.01 Юриспруденция,2018-2019,1.0,2.0,Экзамен,История государства и права России
222396,198675,38.03.01 Экономика,2018-2019,2.0,3.0,Дифференцированный зачет,Иностранный язык в сфере профессиональной комм...
271996,162111,44.03.05 Педагогическое образование (с двумя п...,2018-2019,3.0,6.0,Экзамен,Физическая химия

## A common mark for every student

res = []
for i in range(x_test_send.shape[0]):
    print(i,'/',x_test_send.shape[0],end='\r')
    stdid = x_test_send['STD_ID'].iloc[i]
    marks = list(y_train_in[x_train_in['STD_ID']==stdid].iloc[:,0])
    stats = [marks.count(3), marks.count(4), marks.count(5)]
    res.append(transl[common])
res = np.array(res)

resDf = pd.DataFrame(res,index=x_test_send.index,columns=['mark'])
resDf.index = resDf.index.rename('index')

## NN

In [35]:
course =